variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_STRATEGY: clone

stages:
  - desktop
  - installer

.tags_manual: &tags_manual
  rules:
    - if: '$CI_COMMIT_TAG'
      when: manual
    - when: never

# -------------------------
# DESKTOP
# -------------------------

desktop:unstable:
  stage: desktop
  <<: *tags_manual
  trigger:
    include:
      - local: .gitlab-ci-desktop-deploy.yml
    strategy: depend
  variables:
    DEPLOY_APP_NAME: "Grayjay.Desktop.Unstable"

desktop:stable:
  stage: desktop
  <<: *tags_manual
  trigger:
    include:
      - local: .gitlab-ci-desktop-deploy.yml
    strategy: depend
  variables:
    DEPLOY_APP_NAME: "Grayjay.Desktop"

# -------------------------
# INSTALLER
# -------------------------

buildAndDeployStableWindowsInstaller:
  stage: installer
  tags: [WindowsBuilder]
  <<: *tags_manual
  script:
    - Write-Host $CI_COMMIT_TAG
    - bash deploy_windows_installer.sh
  artifacts:
    paths:
      - Grayjay.Desktop.Installer/Output/Grayjay-1.0.0-Setup-x64.exe
    expire_in: 1d
