stages:
  - pre
  - deploy
  - post

.tags_auto: &tags_auto
  rules:
    - if: '$CI_COMMIT_TAG'
      when: on_success
    - when: never

.tags_always: &tags_always
  rules:
    - if: '$CI_COMMIT_TAG'
      when: always
    - when: never

desktop:maintenance_on:
  stage: pre
  tags: [LinuxBuilder]
  <<: *tags_auto
  script:
    - bash remote_maintenance.sh on "$UPDATER_SERVER" "$DEPLOY_APP_NAME"

desktop:windows:
  stage: deploy
  tags: [WindowsBuilder]
  <<: *tags_auto
  script:
    - Write-Host $CI_COMMIT_TAG
    - bash deploy_windows.sh "$CI_COMMIT_TAG" "$UPDATER_SERVER" "$DEPLOY_APP_NAME"
  artifacts:
    paths:
      - Grayjay.Desktop.CEF/bin/Release/net8.0/win-x64/Grayjay.Desktop-win-x64-v$CI_COMMIT_TAG.zip
    expire_in: 30d

desktop:linux:
  stage: deploy
  tags: [LinuxBuilder]
  <<: *tags_auto
  script:
    - bash deploy_linux.sh "$CI_COMMIT_TAG" "$UPDATER_SERVER" "$DEPLOY_APP_NAME"
  artifacts:
    paths:
      - Grayjay.Desktop.CEF/bin/Release/net8.0/linux-x64/Grayjay.Desktop-linux-x64-v$CI_COMMIT_TAG.zip
    expire_in: 30d

desktop:post:
  stage: post
  tags: [LinuxBuilder]
  <<: *tags_always
  script:
    - |
      set -euo pipefail

      cleanup() {
        bash remote_maintenance.sh off "$UPDATER_SERVER" "$DEPLOY_APP_NAME" || true
      }
      trap cleanup EXIT INT TERM

      bash cloudflare_purge_desktop.sh "$DEPLOY_APP_NAME" "$CI_COMMIT_TAG"
